## Daniel Hoogerwerf's Colorful oh-my-zsh prompt :)
##
## This prompt is created for Mac OS, but with some adjustments it should work for Windows or Linux.
##
## Requirements:
## In order to use this correctly, you first need to have brew installed with the following packages:
## 1. zsh
## 2. zsh-syntax-highlighting
## 3. nvm (see prework on how to installed it)
## 4. powerlevel9k (use the commands: brew tap sambadevi/powerlevel9k && brew install powerlevel9k)
## 5. I use the Hack Nerd Font for my terminal, which can be downloaded here: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack
##    This font will have all the necessary icons used within the prompt, and also for Powerlevel9k
##
## If you use windows, check the url: https://twasa.ml/post/wsl/ to see if you can install the needed packages)
## 
## After, just reconfigure the following parameters for your environment. Takes a little puzzling but you'll get there :)
## If you use Windows, make sure you compare the default oh-my-zsh .zshrc with this one in regards to some paths or settings which will be different.

# If you come from bash you might have to change your $PATH.
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/daniel/.oh-my-zsh" # CHANGE THIS FOR YOUR OWN DIRECTORY
ZSH_THEME="robbyrussell"
HIST_STAMPS="dd/mm/yyyy"

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  git
)

# Oh my ZSH loading
source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8
export HOMEBREW_NO_ANALYTICS=1 ## Brew analytics which I like to turn off. Mac OS only.

# Activate syntax highlighting
# More info: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[command]='fg=144'
ZSH_HIGHLIGHT_STYLES[hashed_command]='fg=144'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=144'
ZSH_HIGHLIGHT_STYLES[alias]='fg=144'

# Added for Ironhack
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# Aliases
alias ls='ls -AlFGh'

# Powerline Configuration
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=' '

# Powerline Prompt Data
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir custom_git_pair vcs)
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%F{008}\uf460%F{008}'
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=$'%F{239}\u2771%F{244}\u2771%F{214}\u2771 '
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status nvm)
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%F{008}\uf104%F{008}'
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" \uf101 "
#POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{008}/%F{166}"
POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{008}/%F{249}"
#POWERLEVEL9K_SHORTEN_DELIMITER='%F{008} …%F{008}'
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
#POWERLEVEL9K_SHORTEN_STRATEGY="none"
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \uE868  %d.%m.%y}"

# VCS Show commit hash (or not)
#POWERLEVEL9K_SHOW_CHANGESET=true

# Powerline Color Definitions
POWERLEVEL9K_DIR_BACKGROUND='237'
POWERLEVEL9K_CUSTOM_GIT_PAIR_BACKGROUND="clear"
POWERLEVEL9K_CUSTOM_GIT_PAIR_FOREGROUND="blue"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"
#POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="208"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="214"
POWERLEVEL9K_DIR_FOREGROUND='010'
POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_FOREGROUND="214"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="214"
POWERLEVEL9K_DIR_ETC_BACKGROUND="clear"
POWERLEVEL9K_DIR_ETC_FOREGROUND="220"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"
POWERLEVEL9K_GO_VERSION_BACKGROUND='clear'
POWERLEVEL9K_GO_VERSION_FOREGROUND='081'
POWERLEVEL9K_NVM_BACKGROUND='clear'
POWERLEVEL9K_NVM_FOREGROUND='green'
POWERLEVEL9K_OS_ICON_BACKGROUND='clear'
POWERLEVEL9K_OS_ICON_FOREGROUND='cyan'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="001"
POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"
POWERLEVEL9K_STATUS_BACKGROUND="clear"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='clear'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='clear'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='220'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='clear'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='197'

# Custom Icons for Powerlevel9k
POWERLEVEL9K_CUSTOM_GIT_PAIR_ICON=$'\uF7AF '
POWERLEVEL9K_ANDROID_ICON=$'\uE70E '
POWERLEVEL9K_APPLE_ICON=$'\uE711 '
POWERLEVEL9K_AWS_ICON=$'\uF52C '
POWERLEVEL9K_AWS_EB_ICON=$'\uE782 '
POWERLEVEL9K_BATTERY_ICON=$'\uF578 '
POWERLEVEL9K_BACKGROUND_JOBS_ICON=$'\uE615 '
POWERLEVEL9K_CARRIAGE_RETURN_ICON=$'\uF54D '
POWERLEVEL9K_DATE_ICON=$='\uF073 '
POWERLEVEL9K_DISK_ICON=$'\uF748 '
POWERLEVEL9K_DROPBOX_ICON=$'\uF16B '
POWERLEVEL9K_ETC_ICON=$'\uF085 '
POWERLEVEL9K_FOLDER_ICON=$'\uF07C '
POWERLEVEL9K_FREEBSD_ICON=$'\uF30C '
POWERLEVEL9K_GO_ICON=$'\uE627 '
POWERLEVEL9K_HOME_ICON=$'\uF015 '
POWERLEVEL9K_HOME_SUB_ICON=$'\uF2BD '
POWERLEVEL9K_JAVA_ICON=$'\uE751 '
POWERLEVEL9K_KUBERNETES_ICON=$'\uF1AA '
POWERLEVEL9K_LARAVEL_ICON=$'\uE73F '
POWERLEVEL9K_LINUX_ALPINE_ICON=$'\uF300 '
POWERLEVEL9K_LINUX_ARCH_ICON=$'\uF303 '
POWERLEVEL9K_LINUX_AOSC_ICON=$'\uF301 '
POWERLEVEL9K_LINUX_CENTOS_ICON=$'\uF304 '
POWERLEVEL9K_LINUX_COREOS_ICON=$'\uF305 '
POWERLEVEL9K_LINUX_DEBIAN_ICON=$'\uF306 '
POWERLEVEL9K_LINUX_ELEMENTARY_ICON=$'\uF309 '
POWERLEVEL9K_LINUX_FEDORA_ICON=$'\uF30A '
POWERLEVEL9K_LINUX_GENTOO_ICON=$'\uF30D '
POWERLEVEL9K_LINUX_ICON=$'\uF83C '
POWERLEVEL9K_LINUX_MAGEIA_ICON=$'\uF310 '
POWERLEVEL9K_LINUX_MANJARO_ICON=$'\uF312 '
POWERLEVEL9K_LINUX_MINT_ICON=$'\uF30E '
POWERLEVEL9K_LINUX_NIXOS_ICON=$'\uF313 '
POWERLEVEL9K_LINUX_OPENSUSE_ICON=$'\uF314 '
POWERLEVEL9K_LINUX_SABAYON_ICON=$'\uF317 '
POWERLEVEL9K_LINUX_SLACKWARE_ICON=$'\uF318 '
POWERLEVEL9K_LINUX_UBUNTU_ICON=$'\uF31C '
POWERLEVEL9K_LOAD_ICON=$'\uF6BA '
POWERLEVEL9K_LOCK_ICON=$'\uF023 '
POWERLEVEL9K_NETWORK_ICON=$'\uF99E '
POWERLEVEL9K_NODE_ICON=$'\uE718 '
POWERLEVEL9K_OK_ICON=$'\uF62B '
POWERLEVEL9K_PUBLIC_IP_ICON=$'\uF968 '
POWERLEVEL9K_PYTHON_ICON=$'\uF81F '
POWERLEVEL9K_RAM_ICON=$'\uF2DB '
POWERLEVEL9K_ROOT_ICON=$'\uF0F0 '
POWERLEVEL9K_RUBY_ICON=$'\uE23E '
POWERLEVEL9K_RUST_ICON=$'\uE7A8 '
POWERLEVEL9K_SERVER_ICON=$'\uF98A '
POWERLEVEL9K_SSH_ICON=$'\uF98C '
POWERLEVEL9K_SUDO_ICON=$'\uF23E '
POWERLEVEL9K_SWAP_ICON=$'\uF9E0 '
POWERLEVEL9K_SWIFT_ICON=$'\uE755 '
POWERLEVEL9K_SYMFONY_ICON=$'\uE756 '
#POWERLEVEL9K_TEST_ICON=$'\uE7A0 '
POWERLEVEL9K_TEST_ICON=$'\uFB67 '
POWERLEVEL9K_TIME_ICON=$'\uF43A '
POWERLEVEL9K_TODO_ICON=$'\uF4A0 '
POWERLEVEL9K_VCS_BOOKMARK_ICON=$'\uF461'
POWERLEVEL9K_VCS_BRANCH_ICON=$'\uF126 '
POWERLEVEL9K_VCS_COMMIT_ICON=$'\uE729 '
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=$'\uF171'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uE708'
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uF296'
POWERLEVEL9K_VCS_GIT_ICON=$'\uF7A1'
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uF527'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uF47C'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uF47B'
POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'\uF484 \uF418 '
POWERLEVEL9K_VCS_STAGED_ICON=$'\uF457'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uF459'
POWERLEVEL9K_VPN_ICON=$'\uF991 '
POWERLEVEL9K_WINDOWS_ICON=$'\uE70F '

source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme
